name: krishi_link
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

 
 
  cupertino_icons: ^1.0.8 
 
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  provider: ^6.1.5
  image_picker: ^1.0.4
  firebase_storage: ^13.0.0
  firebase_storage_web: ^3.10.12
  cloud_firestore_web: ^5.0.0
  # flutter_gen is a code generator; keep it in dev_dependencies instead
  get: ^4.7.2
  flutter_native_splash: ^2.4.6
  dio: ^5.8.0+1
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.3
  api_sdk: ^0.0.8
  http: ^1.4.0
  intl: 0.20.2
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  logger: ^2.5.0
  share_plus: ^11.0.0
  lottie: ^3.3.1
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  async: ^2.13.0
  animate_do: ^4.2.0
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.2.7
  visibility_detector: ^0.4.0+2
  file_picker: 10.3.3
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.9.0
  pin_code_fields: ^8.0.1
  uuid: ^4.5.1
  share_plus_platform_interface: ^6.0.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  path: ^1.9.1
  flutter_animate: ^4.5.0
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  http_parser: ^4.1.2
  geolocator: ^14.0.2
  googlemaps_flutter_webservices: ^1.0.2
  google_maps_flutter: ^2.12.3
  flutter_google_places_sdk: ^0.4.2+1
  geocoding: ^4.0.0
  # Chat Feature Dependencies
  signalr_netcore: ^1.4.0
 
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  video_player: ^2.8.3
  web_socket_channel: ^3.0.2
  # audio_waveforms: ^1.0.4  # Temporarily disabled due to platform compatibility issues
  # record: ^4.4.4  # Temporarily disabled due to platform compatibility issues
  # permission_handler: ^12.0.0+1
  connectivity_plus: ^6.0.5
  flutter_image_compress: ^2.4.0
  go_router: ^16.2.0 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logging: ^1.3.0
  equatable: ^2.0.7
  khalti: ^0.0.1
  flutter_inappwebview: ^6.1.5
  khalti_checkout_flutter: ^1.0.0-dev.9
  completer_ex: ^4.0.3


  # workmanager: ^0.5.2  # Temporarily disabled due to platform compatibility issues
  # Payment Dependencies
  # khalti_flutter: ^1.0.0-dev.5  # Temporarily disabled due to intl version conflict

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation tools (dev-only)
  build_runner: 2.4.11
  hive_generator: 2.0.1
  flutter_gen: ^5.9.0


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/src/core/assets/images/
    - lib/src/core/assets/lottie/
    - lib/src/core/assets/images/krishilink.png
    - lib/src/core/components/lottie/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
# flutter_native_splash:
#   color: "#ffffff" # or any background color
#   image: assets/images/krishilink.jpg # path to your image
#   android_gravity: center 
#   # branding: assets/images/branding.png # optional, like "Powered by"
#   android: true
#   ios: true
